=== Kinger1999/hadoop-mapreduce/target/test-classes/schemas/product-ingest-schema.json
{"definitions":{},"$schema":"http://json-schema.org/draft-06/schema#","$id":"http://example.com/example.json","type":"object","properties":{"job_uuid":{"$id":"/properties/job_uuid","type":"string","title":"The Job_uuid Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["ed42aa74-a012-4bfe-a4ae-15d2edfeb7d3"]},"product_key":{"$id":"/properties/product_key","type":"string","title":"The Product_key Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["52223bdb-e4cc-497a-8ef4-555e8149d3a5"]},"retailer_id":{"$id":"/properties/retailer_id","type":"integer","title":"The Retailer_id Schema.","description":"An explanation about the purpose of this instance.","default":0,"examples":[125]},"retailer_name":{"$id":"/properties/retailer_name","type":"string","title":"The Retailer_name Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["iTunes"]},"created_at":{"$id":"/properties/created_at","type":"string","title":"The Created_at Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["2017-12-24T07:51:04.393Z"]},"updated_at":{"$id":"/properties/updated_at","type":"string","title":"The Updated_at Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["2017-12-27T07:51:04.057Z"]},"product_id":{"$id":"/properties/product_id","type":"string","title":"The Product_id Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["1161504043"]},"name":{"$id":"/properties/name","type":"string","title":"The Name Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["That’s What I Like"]},"image_url_retailer":{"$id":"/properties/image_url_retailer","type":"string","title":"The Image_url_retailer Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["http://is2.mzstatic.com/image/thumb/Music62/v4/40/98/ed/4098edc3-1ae9-4da7-4778-b9d3b8b2a846/075679904119.jpg/600x600bb-85.jpg"]},"deeplink_url":{"$id":"/properties/deeplink_url","type":"string","title":"The Deeplink_url Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["https://itunes.apple.com/us/album/thats-what-i-like/1161503945?i=1161504043&uo=2"]},"product_type":{"$id":"/properties/product_type","type":"array","items":{"$id":"/properties/product_type/items","type":"string","title":"The 0 Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["Music"]}},"price":{"$id":"/properties/price","type":"number","title":"The Price Schema.","description":"An explanation about the purpose of this instance.","default":0,"examples":[1.2899999618530273]},"searchable_metadata":{"$id":"/properties/searchable_metadata","type":"array","items":{"$id":"/properties/searchable_metadata/items","type":"object","properties":{"name":{"$id":"/properties/searchable_metadata/items/properties/name","type":"string","title":"The Name Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["copyright"]},"value":{"$id":"/properties/searchable_metadata/items/properties/value","type":"string","title":"The Value Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["℗ 2016 Atlantic Recording Corporation for the United States and WEA International Inc. for the world outside of the United States. A Warner Music Group Company"]}}}},"id":{"$id":"/properties/id","type":"string","title":"The Id Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["125:1161504043"]},"start_time":{"$id":"/properties/start_time","type":"string","title":"The Start_time Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["2017-12-24T07:51:04.393Z"]},"end_time":{"$id":"/properties/end_time","type":"string","title":"The End_time Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["2067-12-27T07:51:04.057Z"]},"expiration":{"$id":"/properties/expiration","type":"string","title":"The Expiration Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["2067-12-27T07:51:04.057Z"]},"typed_id":{"$id":"/properties/typed_id","type":"string","title":"The Typed_id Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["prd:125:1161504043"]},"typed_prereq_id":{"$id":"/properties/typed_prereq_id","type":"string","title":"The Typed_prereq_id Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["prd:0"]},"typed_scoring_id":{"$id":"/properties/typed_scoring_id","type":"string","title":"The Typed_scoring_id Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["prd:125:1161504043"]},"launch":{"$id":"/properties/launch","type":"boolean","title":"The Launch Schema.","description":"An explanation about the purpose of this instance.","default":false,"examples":[true]},"active":{"$id":"/properties/active","type":"boolean","title":"The Active Schema.","description":"An explanation about the purpose of this instance.","default":false,"examples":[true]},"matching_rules":{"$id":"/properties/matching_rules","type":"string","title":"The Matching_rules Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"rules\":[]}"]},"image_url_thumbnail":{"$id":"/properties/image_url_thumbnail","type":"string","title":"The Image_url_thumbnail Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["https://d34iyr7lamo4bp.cloudfront.net/125:1161504043/thumbnail.png"]},"image_url_small":{"$id":"/properties/image_url_small","type":"string","title":"The Image_url_small Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["https://d34iyr7lamo4bp.cloudfront.net/125:1161504043/small.png"]},"image_url_large":{"$id":"/properties/image_url_large","type":"string","title":"The Image_url_large Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["https://d34iyr7lamo4bp.cloudfront.net/125:1161504043/large.png"]},"always_nearby":{"$id":"/properties/always_nearby","type":"boolean","title":"The Always_nearby Schema.","description":"An explanation about the purpose of this instance.","default":false,"examples":[true]},"non_searchable_metadata":{"$id":"/properties/non_searchable_metadata","type":"object","properties":{"im:name":{"$id":"/properties/non_searchable_metadata/properties/im:name","type":"string","title":"The Im:name Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"label\":\"That’s What I Like\"}"]},"im:image":{"$id":"/properties/non_searchable_metadata/properties/im:image","type":"string","title":"The Im:image Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["[{\"label\":\"http://is2.mzstatic.com/image/thumb/Music62/v4/40/98/ed/4098edc3-1ae9-4da7-4778-b9d3b8b2a846/075679904119.jpg/55x55bb-85.jpg\",\"attributes\":{\"height\":\"55\"}},{\"label\":\"http://is3.mzstatic.com/image/thumb/Music62/v4/40/98/ed/4098edc3-1ae9-4da7-4778-b9d3b8b2a846/075679904119.jpg/60x60bb-85.jpg\",\"attributes\":{\"height\":\"60\"}},{\"label\":\"http://is3.mzstatic.com/image/thumb/Music62/v4/40/98/ed/4098edc3-1ae9-4da7-4778-b9d3b8b2a846/075679904119.jpg/170x170bb-85.jpg\",\"attributes\":{\"height\":\"170\"}}]"]},"im:collection":{"$id":"/properties/non_searchable_metadata/properties/im:collection","type":"string","title":"The Im:collection Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"im:name\":{\"label\":\"24K Magic\"},\"link\":{\"attributes\":{\"rel\":\"alternate\",\"type\":\"text/html\",\"href\":\"https://itunes.apple.com/us/album/24k-magic/1161503945?uo=2\"}},\"im:contentType\":{\"im:contentType\":{\"attributes\":{\"term\":\"Album\",\"label\":\"Album\"}},\"attributes\":{\"term\":\"Music\",\"label\":\"Music\"}}}"]},"im:price":{"$id":"/properties/non_searchable_metadata/properties/im:price","type":"string","title":"The Im:price Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"label\":\"$1.29\",\"attributes\":{\"amount\":\"1.29000\",\"currency\":\"USD\"}}"]},"im:contentType":{"$id":"/properties/non_searchable_metadata/properties/im:contentType","type":"string","title":"The Im:contenttype Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"im:contentType\":{\"attributes\":{\"term\":\"Track\",\"label\":\"Track\"}},\"attributes\":{\"term\":\"Music\",\"label\":\"Music\"}}"]},"rights":{"$id":"/properties/non_searchable_metadata/properties/rights","type":"string","title":"The Rights Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"label\":\"℗ 2016 Atlantic Recording Corporation for the United States and WEA International Inc. for the world outside of the United States. A Warner Music Group Company\"}"]},"title":{"$id":"/properties/non_searchable_metadata/properties/title","type":"string","title":"The Title Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"label\":\"That’s What I Like - Bruno Mars\"}"]},"link":{"$id":"/properties/non_searchable_metadata/properties/link","type":"string","title":"The Link Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["[{\"attributes\":{\"rel\":\"alternate\",\"type\":\"text/html\",\"href\":\"https://itunes.apple.com/us/album/thats-what-i-like/1161503945?i=1161504043&uo=2\"}},{\"im:duration\":{\"label\":\"30000\"},\"attributes\":{\"title\":\"Preview\",\"rel\":\"enclosure\",\"type\":\"audio/x-m4a\",\"href\":\"https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/AudioPreview71/v4/ca/7f/28/ca7f2818-514a-5a6f-ac63-bd420da38a0c/mzaf_3303110486375225949.plus.aac.p.m4a\",\"im:assetType\":\"preview\"}}]"]},"id":{"$id":"/properties/non_searchable_metadata/properties/id","type":"string","title":"The Id Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"label\":\"https://itunes.apple.com/us/album/thats-what-i-like/1161503945?i=1161504043&uo=2\",\"attributes\":{\"im:id\":\"1161504043\"}}"]},"im:artist":{"$id":"/properties/non_searchable_metadata/properties/im:artist","type":"string","title":"The Im:artist Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"label\":\"Bruno Mars\",\"attributes\":{\"href\":\"https://itunes.apple.com/us/artist/bruno-mars/278873078?uo=2\"}}"]},"category":{"$id":"/properties/non_searchable_metadata/properties/category","type":"string","title":"The Category Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"attributes\":{\"im:id\":\"14\",\"term\":\"Pop\",\"scheme\":\"https://itunes.apple.com/us/genre/music-pop/id14?uo=2\",\"label\":\"Pop\"}}"]},"im:releaseDate":{"$id":"/properties/non_searchable_metadata/properties/im:releaseDate","type":"string","title":"The Im:releasedate Schema.","description":"An explanation about the purpose of this instance.","default":"","examples":["{\"label\":\"2016-11-18T00:00:00-07:00\",\"attributes\":{\"label\":\"November 18, 2016\"}}"]}}}}}

=== Kinger1999/hadoop-mapreduce/src/test/resources/data/product-ingest-valid-data.json
{"job_uuid":"ed42aa74-a012-4bfe-a4ae-15d2edfeb7d3","product_key":"52223bdb-e4cc-497a-8ef4-555e8149d3a5","retailer_id":125,"retailer_name":"iTunes","created_at":"2017-12-24T07:51:04.393Z","updated_at":"2017-12-27T07:51:04.057Z","product_id":"1161504043","name":"That’s What I Like","image_url_retailer":"http://is2.mzstatic.com/image/thumb/Music62/v4/40/98/ed/4098edc3-1ae9-4da7-4778-b9d3b8b2a846/075679904119.jpg/600x600bb-85.jpg","deeplink_url":"https://itunes.apple.com/us/album/thats-what-i-like/1161503945?i=1161504043&uo=2","product_type":["Music","Track"],"price":1.29,"searchable_metadata":[{"name":"copyright","value":"℗ 2016 Atlantic Recording Corporation for the United States and WEA International Inc. for the world outside of the United States. A Warner Music Group Company"},{"name":"genre","value":"Pop"},{"name":"preview_url","value":"https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/AudioPreview71/v4/ca/7f/28/ca7f2818-514a-5a6f-ac63-bd420da38a0c/mzaf_3303110486375225949.plus.aac.p.m4a"},{"name":"release_date","value":"2016-11-18T00:00:00-07:00"},{"name":"album","value":"24K Magic"},{"name":"album_url","value":"https://itunes.apple.com/us/album/24k-magic/1161503945?uo=2"},{"name":"artist","value":"Bruno Mars"},{"name":"artist_url","value":"https://itunes.apple.com/us/artist/bruno-mars/278873078?uo=2"}],"id":"125:1161504043","start_time":"2017-12-24T07:51:04.393Z","end_time":"2067-12-27T07:51:04.057Z","expiration":"2067-12-27T07:51:04.057Z","typed_id":"prd:125:1161504043","typed_prereq_id":"prd:0","typed_scoring_id":"prd:125:1161504043","launch":true,"active":true,"matching_rules":"{\"rules\":[]}","image_url_thumbnail":"https://d34iyr7lamo4bp.cloudfront.net/125:1161504043/thumbnail.png","image_url_small":"https://d34iyr7lamo4bp.cloudfront.net/125:1161504043/small.png","image_url_large":"https://d34iyr7lamo4bp.cloudfront.net/125:1161504043/large.png","always_nearby":true,"non_searchable_metadata":{"im:name":"{\"label\":\"That’s What I Like\"}","im:image":"[{\"label\":\"http://is2.mzstatic.com/image/thumb/Music62/v4/40/98/ed/4098edc3-1ae9-4da7-4778-b9d3b8b2a846/075679904119.jpg/55x55bb-85.jpg\",\"attributes\":{\"height\":\"55\"}},{\"label\":\"http://is3.mzstatic.com/image/thumb/Music62/v4/40/98/ed/4098edc3-1ae9-4da7-4778-b9d3b8b2a846/075679904119.jpg/60x60bb-85.jpg\",\"attributes\":{\"height\":\"60\"}},{\"label\":\"http://is3.mzstatic.com/image/thumb/Music62/v4/40/98/ed/4098edc3-1ae9-4da7-4778-b9d3b8b2a846/075679904119.jpg/170x170bb-85.jpg\",\"attributes\":{\"height\":\"170\"}}]","im:collection":"{\"im:name\":{\"label\":\"24K Magic\"},\"link\":{\"attributes\":{\"rel\":\"alternate\",\"type\":\"text/html\",\"href\":\"https://itunes.apple.com/us/album/24k-magic/1161503945?uo=2\"}},\"im:contentType\":{\"im:contentType\":{\"attributes\":{\"term\":\"Album\",\"label\":\"Album\"}},\"attributes\":{\"term\":\"Music\",\"label\":\"Music\"}}}","im:price":"{\"label\":\"$1.29\",\"attributes\":{\"amount\":\"1.29000\",\"currency\":\"USD\"}}","im:contentType":"{\"im:contentType\":{\"attributes\":{\"term\":\"Track\",\"label\":\"Track\"}},\"attributes\":{\"term\":\"Music\",\"label\":\"Music\"}}","rights":"{\"label\":\"℗ 2016 Atlantic Recording Corporation for the United States and WEA International Inc. for the world outside of the United States. A Warner Music Group Company\"}","title":"{\"label\":\"That’s What I Like - Bruno Mars\"}","link":"[{\"attributes\":{\"rel\":\"alternate\",\"type\":\"text/html\",\"href\":\"https://itunes.apple.com/us/album/thats-what-i-like/1161503945?i=1161504043&uo=2\"}},{\"im:duration\":{\"label\":\"30000\"},\"attributes\":{\"title\":\"Preview\",\"rel\":\"enclosure\",\"type\":\"audio/x-m4a\",\"href\":\"https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/AudioPreview71/v4/ca/7f/28/ca7f2818-514a-5a6f-ac63-bd420da38a0c/mzaf_3303110486375225949.plus.aac.p.m4a\",\"im:assetType\":\"preview\"}}]","id":"{\"label\":\"https://itunes.apple.com/us/album/thats-what-i-like/1161503945?i=1161504043&uo=2\",\"attributes\":{\"im:id\":\"1161504043\"}}","im:artist":"{\"label\":\"Bruno Mars\",\"attributes\":{\"href\":\"https://itunes.apple.com/us/artist/bruno-mars/278873078?uo=2\"}}","category":"{\"attributes\":{\"im:id\":\"14\",\"term\":\"Pop\",\"scheme\":\"https://itunes.apple.com/us/genre/music-pop/id14?uo=2\",\"label\":\"Pop\"}}","im:releaseDate":"{\"label\":\"2016-11-18T00:00:00-07:00\",\"attributes\":{\"label\":\"November 18, 2016\"}}"}}
